- name: Create a libvirt VM
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Define libvirt vm from xml template
    community.libvirt.virt:
      uri: "qemu://192.168.100.1/system"
      command: define
      xml: "{{ lookup('template', 'files/dom_template.xml.j2') }}"
