---
- name: Create a libvirt VM
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Define libvirt vm from xml template
    community.libvirt.virt:
      command: define
      xml: "{{ lookup('template', 'files/vm_template.xml.j2') }}"
