---
- name: play 1 which sets a data for next plays
  hosts: localhost
  vars:
  - testdata: 123

  tasks:
  - name: set stats for test
    ansible.builtin.set_stats:
      data:
        testdata: "{{ testdata }}"
