---
- name: test libvirt modules
  hosts: localhost
  connection: local
  tasks:
  - name: list VM's
    community.libvirt.virt:
      uri: "qemu://192.168.100.1/system"
      command: list_vms
    register: all_vms
    
  - name: show result
    ansible.builtin.debug:
      var: all_vms
