---
- name: test libvirt modules
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: list VM's
    community.libvirt.virt:
      uri: "qemu://192.168.100.1/system"
      command: list_vms
    register: all_vms
    
  - name: show result
    ansible.builtin.debug:
      var: all_vms

  - name: show username from machine_credential
    ansible.builtin.debug:
      msg: "-{{ ansible_user }}-"

  - name: show password from machine credential
    ansible.builtin.debug:
      msg: "-{{ ansible_password }}-"
